import { NextRequest, NextResponse } from "next/server";
import { runRagPipeline } from "@/lib/ai/rag";
import { getVectorStore } from "@/lib/vector-store";

export const dynamic = "force-dynamic";

/**
 * POST /api/chat
 * RAG Chat endpoint supporting real-time token streaming and source citations.
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { message, documentId, history } = body;

    if (!message || typeof message !== "string" || message.trim() === "") {
      return NextResponse.json(
        { error: "Message prompt is required." },
        { status: 400 }
      );
    }

    const store = getVectorStore();
    if (store.totalChunks === 0) {
      return NextResponse.json(
        {
          error:
            "No documents uploaded yet. Please upload a PDF or document in the left sidebar first.",
        },
        { status: 400 }
      );
    }

    // Run the RAG pipeline
    const { stream, sources } = await runRagPipeline({
      question: message.trim(),
      documentId: documentId || undefined,
      history,
    });

    // Create a TextEncoder to stream Server-Sent Events (SSE)
    const encoder = new TextEncoder();

    const readable = new ReadableStream({
      async start(controller) {
        try {
          // 1. Send source citations first
          const sourcesPayload = JSON.stringify({
            type: "sources",
            data: sources,
          });
          controller.enqueue(encoder.encode(`data: ${sourcesPayload}\n\n`));

          // 2. Stream tokens as they are generated by Gemini
          for await (const chunk of stream) {
            const tokenContent = typeof chunk.content === "string" ? chunk.content : "";
            if (tokenContent) {
              const tokenPayload = JSON.stringify({
                type: "token",
                content: tokenContent,
              });
              controller.enqueue(encoder.encode(`data: ${tokenPayload}\n\n`));
            }
          }

          // 3. Send done event
          controller.enqueue(
            encoder.encode(`data: ${JSON.stringify({ type: "done" })}\n\n`)
          );
          controller.close();
        } catch (streamError) {
          console.error("Streaming error in /api/chat:", streamError);
          const errorPayload = JSON.stringify({
            type: "error",
            message:
              streamError instanceof Error
                ? streamError.message
                : "Error during response generation.",
          });
          controller.enqueue(encoder.encode(`data: ${errorPayload}\n\n`));
          controller.close();
        }
      },
    });

    return new Response(readable, {
      headers: {
        "Content-Type": "text/event-stream; charset=utf-8",
        "Cache-Control": "no-cache, no-transform",
        Connection: "keep-alive",
      },
    });
  } catch (error: unknown) {
    console.error("Error in /api/chat route:", error);
    const message =
      error instanceof Error ? error.message : "Internal server error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
